### ISSUE TITLE
Error in checkpoints when trying to load a saved model

### ISSUE THREAD

**Issue by agarwal-shubham** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#1]
I get this error - unknown Torch class nn.Sequencer
when i was trying to create a demo file which returns test results on the data for a particular trained epoch/model
it originates from the following line in checkpoints.lua
"local latest=torch.load(latestPath)"

**Comment by cmhungsteve** [comment]
That means your path is not correct. It depends on your setting.

**Comment by agarwal-shubham** [comment]
I figured it out, actually we need to require the nn and rnn libraries in checkouts.lua too, it works while training because it accesses the model first there which does that.
thanks anyway
