### ISSUE TITLE
the meaning of "Fine-tune" in the table 1

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#10]
Thanks for your nice job! @chihyaoma 
I have read your paper carfully, I want to know the meaning of "Fine-tune" in the table 1. 
It means the "Cross modality pre-training"  in the TSN paper?

**Comment by cmhungsteve** [comment]
The general idea is the same.
In our implementation, we use the model trained from the RGB modality as the pre-trained model for optical-flow modality.
