### ISSUE TITLE
running optical_flow.cpp error

### ISSUE THREAD

**Issue by Datasharing-wow** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#11]
When I built optical_flow.cpp with eclips,therr're two errors came out.
The errors came out in line 369 and 373:
cvtColor(cv::Mat&, cv::Mat&, <anonymous enum>) is ambiguous

I just don't how to solve this.

**Comment by cmhungsteve** [comment]
maybe you didn't specify the namespace
