### ISSUE TITLE
CNN-Pred-Feat/run_pred-feat_twoStreams.lua   error

### ISSUE THREAD

**Issue by Ameelisy** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#13]
(around line 401-404)
(existTr = opt.save and paths.filep(namePredTr) and paths.filep(nameFeatTr[1]) and paths.filep(nameFeatTr[2])
	Tr = {} -- output prediction & info
	featTr = {}
	if not existData then)
I think existData should be changed to existTr, because there is no variable existData in the context. is that true?

**Comment by cmhungsteve** [comment]
You're right. Thank you.
