### ISSUE TITLE
cannot generating features 

### ISSUE THREAD

**Issue by Datasharing-wow** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#14]
@chihyaoma @cmhungsteve 
Hi:
in folder CNN-Pred-Feat,when i run the command to generate feature,I got error below:

split #: 1	
...
==> Processing all the videos...	
Current Class: 1. ApplyEyeMakeup	
[mpeg4 @ 0x7f45937175a0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7f4594342ac0] Invalid and inefficient vfw-avi packed B frames detected
/home/user/torch/install/bin/luajit: bad argument #2 to '?' (start index out of bound at /tmp/luarocks_torch-scm-1-2915/torch7/generic/Tensor.c:984)
stack traceback:
	[C]: at 0x7f4636095bd0
	[C]: in function '__index'
	run_pred-feat_twoStreams.lua:679: in main chunk
	[C]: in function 'dofile'
	...tune/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
...

The first problem is "[mpeg4 @ ...] Invalid and inefficient vfw-avi packed B frames detected"
The second problem is "/torch/install/bin/luajit:  bad argument #2 to '?' (start index out of bound at /tmp/luarocks_torch-scm-1-2915/torch7/generic/Tensor.c:984)"

I don't know how to fixed these problems...

And how to prepare the dataset,do I have to extract RGB and optical frames into jpg files from video?

**Comment by Ameelisy** [comment]
you maybe not correct your code, please see:
https://github.com/chihyaoma/Activity-Recognition-with-CNN-and-RNN/issues/13

**Comment by Ameelisy** [comment]
hi, how do you configure your Video Decoder Library for Torch, when I configured it, it appears an error.
could you give me your configure steps? thank you.

**Comment by Datasharing-wow** [comment]
Hi.this is my install step:
step1:download torch-toolbox into "~/torch/pkg/"
step2:cd video-decoder 
step3:make
step4:make install
step5:install ffmpeg follow the normal steps
$ luarocks install ffmpeg
$ sudo add-apt-repository ppa:mc3man/trusty-media
$ sudo apt-get update
$ sudo apt-get dist-upgrade
$ sudo apt-get install ffmpeg

**Comment by Datasharing-wow** [comment]
@chihyaoma @cmhungsteve 
I found a mistake at line 525,
line 525: " table.sort(nameSubVideo) -- ascending order"
"nameSubVideo" have to be "nameSubVideoTemp"
Without changing,the program will stop at line 679.

**Comment by Ameelisy** [comment]
thank you very much

**Comment by Ameelisy** [comment]
when I run at step3, I met an error, did you meet before?

**Comment by Datasharing-wow** [comment]
Yes,if I use lua 5.2,will get lots of errors.
But if I install torch without lua5.2(just use luaJIT)
It'll compile successfully.

**Comment by Ameelisy** [comment]
ok, thank you, i will try it immediately

**Comment by Ameelisy** [comment]
@Datasharing-wow 
I also found the mistake at line 525,
"nameSubVideo" have to be "nameSubVideoTemp"
you are right!
thank you for share.
