### ISSUE TITLE
/CNN-Pred-Feat/    error

### ISSUE THREAD

**Issue by Ameelisy** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#15]
@chihyaoma  @cmhungsteve 
when I configure the Torch Video Decoder Library, it appears  an error, My steps to configure the environment are as follows：

$ sudo add-apt-repository ppa:mc3man/trusty-media
$ sudo apt-get update
$ sudo apt-get dist-upgrade
$ sudo apt-get install ffmpeg
$ luarocks install ffmpeg

sudo apt-get install -y libavformat-dev libavutil-dev libavcodec-dev libswscale-dev libfreetype6-dev

then I go to torch-toolbox/Video-decoder/ and make, it appears an error, and I do not know how to solve it:

user@2017:~/torch-toolbox-master/Video-decoder$ make
gcc -O3 -c -fpic -Wall -DDOVIDEOCAP -I. -I/home/user/torch/install/include -I/usr/include/freetype2 video_decoder.c
video_decoder.c:3065:30: error: array type has incomplete element type ‘struct luaL_reg’
 static const struct luaL_reg video_decoder[] = {
                              ^
video_decoder.c: In function ‘luaopen_libvideo_decoder’:
video_decoder.c:3094:2: warning: implicit declaration of function ‘luaL_register’ [-Wimplicit-function-declaration]
  luaL_register(L, "libvideo_decoder", video_decoder);
  ^
In file included from video_decoder.c:13:0:
video_decoder.c: At top level:
/home/user/torch/install/include/luaT.h:41:12: warning: ‘luaL_typerror’ defined but not used [-Wunused-function]
 static int luaL_typerror(lua_State *L, int narg, const char *tname)
            ^
video_decoder.c:3065:30: warning: ‘video_decoder’ defined but not used [-Wunused-variable]
 static const struct luaL_reg video_decoder[] = {
                              ^
make: *** [video_decoder.o] Error 1
user@2017:~/torch-toolbox-master/Video-decoder$

**Comment by ash22194** [comment]
How did you solve the problem? When I run `th run_pred-feat_twoStreams.lua` it gives me the following error

> /home/ashwin/ActivityRecognition/torch/install/bin/lua: ...tyRecognition/torch/install/share/lua/5.2/trepl/init.lua:389: module 'libvideo_decoder' not found:No LuaRocks module found for libvideo_decoder
> 	no field package.preload['libvideo_decoder']
> 	no file '/home/ashwin/.luarocks/share/lua/5.2/libvideo_decoder.lua'
> 	no file '/home/ashwin/.luarocks/share/lua/5.2/libvideo_decoder/init.lua'
> 	no file '/home/ashwin/ActivityRecognition/torch/install/share/lua/5.2/libvideo_decoder.lua'
> 	no file '/home/ashwin/ActivityRecognition/torch/install/share/lua/5.2/libvideo_decoder/init.lua'
> 	no file '/home/ashwin/ActivityRecognition/torch/install/lib/lua/5.2/libvideo_decoder.lua'
> 	no file '/home/ashwin/ActivityRecognition/torch/install/lib/lua/5.2/libvideo_decoder/init.lua'
> 	no file './libvideo_decoder.lua'
> 	no file '/home/ashwin/.luarocks/lib/lua/5.2/libvideo_decoder.so'
> 	no file '/home/ashwin/ActivityRecognition/torch/install/lib/lua/5.2/libvideo_decoder.so'
> 	no file '/home/ashwin/ActivityRecognition/torch/install/lib/libvideo_decoder.so'
> 	no file '/home/ashwin/ActivityRecognition/torch/install/lib/lua/5.2/loadall.so'
> 	no file './libvideo_decoder.so'
> stack traceback:
> 	[C]: in function 'error'
> 	...tyRecognition/torch/install/share/lua/5.2/trepl/init.lua:389: in function 'require'
> 	run_pred-feat_twoStreams.lua:25: in main chunk
> 	[C]: in function 'dofile'
> 	...tion/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
> 	[C]: in ?

**Comment by Ameelisy** [comment]
@ash22194    To solve the problem, please see https://github.com/chihyaoma/Activity-Recognition-with-CNN-and-RNN/issues/14
