### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by Aswanykh** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#17]
Hi,

Could you please share the trained model file. I am using a CPU system and training takes a lot of time.

**Comment by cmhungsteve** [comment]
We did share the pre-trained models. They're under `CNN-Pred-Feat/`.

**Comment by LekshmyHari** [comment]
Thank you for the prompt reply. Could you please advice us to how to do testing on a new video using this pre-trained model?

**Comment by cmhungsteve** [comment]
You can check the codes around line 664-722 in `CNN-Pred-Feat/run_pred-feat_twoStreams.lua`. Those pieces of codes are used to forward-pass videos to the model, and then get frame-level feature vectors and video-level prediction. The other parts of codes are used to deal with the whole dataset.
By the way, the pre-trained models under `CNN-Pred-Feat/` are used to get the baseline results. If you want to get the results of `RNN` or `Temporal-ConvNet`, you need to generate the frame-level feature vectors first, and then feed those vectors to the models under `RNN/` or 'Temporal-ConvNet/'.
