### ISSUE TITLE
libvideo_decoder missing

### ISSUE THREAD

**Issue by ash22194** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#20]
Trying to execute `th run_pred-feat_twoStreams.lua`, but the package **libvideo_decoder** is missing. I installed **ffmpeg** using **luarocks** as well as **apt**. Tried using **luarocks** to install **libvideo_decoder**, but it couldn't identify the query. Tried installing the video-decoder from [torch-toolbox](https://github.com/e-lab/torch-toolbox), but it seems it only works with lua5.1 (runs into compile issues when trying to make with lua5.2). 
How do you install the libvideo_decoder package?

**Comment by cmhungsteve** [comment]
we use Lua 5.1. We haven't tried Lua 5.2 yet.
