### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by LiliMeng** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#21]
Hi,
        Thanks a lot for providing the open-source code!
        May I ask how much memory to run the example code? such as 
        $th main.lua -pastalogName 'model_RNN' -nGPU 1 -dataset 'ucf101' -split '1' -fcSize '{0}' -hiddenSize '{512}' -lstm -spatFeatDir '<path/to/feature/>' -tempFeatDir '<path/to/feature/>'  

        My desktop has a Nvidia 1070, but it run out of memory when running this code.
        Thanks a lot!

**Comment by cmhungsteve** [comment]
You can decrease the batch size
