### ISSUE TITLE
the 25th frame of each video not used in segments

### ISSUE THREAD

**Issue by LiliMeng** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#22]
Hi,
     Thanks a lot for your open-source code!
     It seems that only 24 frames per video is used. There are three segments and each segment contains only 8 frames.  Is that correct?
     Highly appreciate your time and help!

**Comment by cmhungsteve** [comment]
We divided 25 frames into 3 segments and decided to drop the last frame. You can try different numbers of frame segments, such as 8-9-8, but I think the performance won't change a lot.
