### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Lelo123** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#23]
Good Afternoon.

I want to create my own dataset with human facial emotions with my own classes.

Is it possible to use it? If it is should i make a feature extraction?

Thanks in advance and sorry, i'm still a newbie on this.

**Comment by cmhungsteve** [comment]
You can follow the following steps:
1. use `CNN-GPUs/` to fine-tune the model with your own classes to train an image model.
2. use `CNN-Pred-Feat/` to load the trained model and your input data to get the feature vectors.
3. use `RNN/` or `Temporal-ConvNet` to train the final model with the feature vectors.
