### ISSUE TITLE
Paper reference for  Temporal CNN 

### ISSUE THREAD

**Issue by pribadihcr** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#3]
Hi @chihyaoma ,

What is the paper reference for the TCNN?
Thanks

**Comment by chihyaoma** [comment]
The TCNN is a temporal convolutional network that we proposed in this project, so there is no paper reference for that for now. However, a paper from Google (as below) also has quite similar idea to our proposed network. In our proposed network, there are actually some variations from their paper. We plan to submit our paper to arXiv anytime soon. Please stay tuned. 

Beyond Short Snippets: Deep Networks for Video Classification
https://arxiv.org/pdf/1503.08909v2.pdf

**Comment by pribadihcr** [comment]
What is the different with C3D ?

**Comment by chihyaoma** [comment]
The C3D has 3D convolutional kernels. Our approach uses 1D convolutional kernels on temporal-constructed feature matrix.
