### ISSUE TITLE
RNN vs Temporal Convnet accuracy?

### ISSUE THREAD

**Issue by anuragranj** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#5]
Any idea about the accuracy with RNNs vs Temporal Convnets? Which is better?

**Comment by chihyaoma** [comment]
We set up a baseline for comparing the two directions (RNN vsTemporal-ConvNet) on UCF101 and HMDB51. 

Our experimental results show that both of them can achieve state-of-the-art performance, but RNNs is slightly better. 

I will post our arXiv paper in the next few days. Please stay tuned.

**Comment by anuragranj** [comment]
Thanks, I look forward to your paper.
