### ISSUE TITLE
How to test a video using a pretrained model?

### ISSUE THREAD

**Issue by WERush** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#6]
Hi,
I want to use your pretrained model to predict my video. How can I make a video-level prediction?
Can you show me a pipeline for the testing?

Thanks

**Comment by chihyaoma** [comment]
Hey, 

I am not sure what do you mean. Can you be more specific? A pre-trained spatial-stream ResNet-101, temporal-stream ResNet-101, TS-LSTM, or Temporal-Inception?

**Comment by WERush** [comment]
Does your model support the video-level prediction? I mean the input is a video. I want to use your total pretrained model to predict my own video. For example, "th test.lua --input_video test.avi".

Thanks.

**Comment by chihyaoma** [comment]
We don't have the code for doing that, but you can certainly local both the two-stream ResNet and combine with either TS-LSTM or Temporal-Inception model for inference. Reading a video can be done by FFmpeg.
