### ISSUE TITLE
Optical_Flow_images

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#7]
Thanks for your shared code and nice job!
Could you please provide the link of the optical flow maps(images) of UCF101 and HMDB? Computing the optical flow is so slow that I have to beg you to help me.  @chihyaoma @cmhungsteve

**Comment by chihyaoma** [comment]
I believe having optical flow videos will be more efficient than image files. 

I just uploaded the optical flow videos for UCF101. You can use any of the methods you like to extract video frames and save them into files. If you do it with multithreading, this process should only take a few hours. 

[UCF101 TV-L1 optical flow videos](https://www.dropbox.com/s/sroft35o9xjs001/UCF101-FlowMap-TVL1-crop20.zip?dl=0)

I will probably provide optical flow videos for HMDB51 in a few days.

**Comment by 3DMM-ICME2023** [comment]
Thanks a million!     Awesome job!
Look forward to optical flow videos for HMDB51.

**Comment by chihyaoma** [comment]
Links for downloading the RGB and TV-L1 videos are now provided in README.md. Please refer to the links to download the optical flow videos you want.
