### ISSUE TITLE
 invalid arguments: DoubleTensor FloatTensor number

### ISSUE THREAD

**Issue by martin-tian** [chihyaoma/Activity-Recognition-with-CNN-and-RNN#9]
@chihyaoma @cmhungsteve 
When I execute : th run.lua -o /root/datasets/trainingData/TC  --dataset UCF-101

give the result as follows :
root@rnn-ThinkServer-TS50X:~/Activity-Recognition-with-CNN-and-RNN/Temporal-ConvNet# th run.lua -o /root/datasets/trainingData/TC  --dataset UCF-101
==> processing options
==> switching to CUDA
==> using GPU #1
==> load data
dirFeature #: /root/datasets/Features/UCF-101/
split #: 1
==> load test data: data_feat_test_RGB_centerCrop_25f_sp1.t7
==> load test data: data_feat_test_FlowMap-TVL1-crop20_centerCrop_25f_sp1.t7
dirFeature #: /root/datasets/Features/UCF-101/
split #: 1
==> load test data: data_feat_test_RGB_centerCrop_25f_sp1.t7
==> load test data: data_feat_test_FlowMap-TVL1-crop20_centerCrop_25f_sp1.t7
/root/torch/install/bin/lua: /root/torch/install/share/lua/5.1/trepl/init.lua:389: invalid arguments: DoubleTensor FloatTensor number
expected arguments: [*DoubleTensor*] DoubleTensor DoubleTensor [index] | [*DoubleTensor*] {DoubleTensor+} [index]
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        run.lua:66: in main chunk
        [C]: in function 'dofile'
        .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: ?

What should I do? ,I need some help

**Comment by martin-tian** [comment]
@chihyaoma @cmhungsteve 
I just changed the file data-2Stream.lua
as follows :
if source == 'local' then
	dirSource = '/home/cmhung/Code/'
elseif source == 'workstation' then	
	--dirSource = '/home/chih-yao/Downloads/'
	dirSource = '/root/datasets/'   --this is my path of dataset
end

**Comment by cmhungsteve** [comment]
You need to double-check the path. 
In line 34, 
dirFeature = dirSource..'Features/'..opt.dataset..'/'
make sure you put the feature files into the correct path. (you may need to create folders like "Features", "UCF-101", ......)
